Script died when therewas a warn() call. This was because warnings was not imported. This caused a failure to convert this puzzle: https://www.xwordinfo.com/Crossword?date=12/29/2024 since it has -'s in it.
Traceback (most recent call last):
  File "/src/xd/puz2xd-standalone.py", line 331, in <module>
    main(fn)
  File "/src/xd/puz2xd-standalone.py", line 326, in main
    xd = parse_puz(open(fn, mode='rb').read(), fn)
  File "/src/xd/puz2xd-standalone.py", line 289, in parse_puz
    warn("%s: unknown grid character '%s', assuming rebus (as '%s')" % (filename, ch, cellch))
NameError: name 'warn' is not defined

Now the script now warns:
/src/xd/puz2xd-standalone.py:290: UserWarning: nyt/NY Times - 20241229 - Multi-Hyphenates.puz: unknown grid character '-', assuming rebus (as '1')
  warnings.warn("%s: unknown grid character '%s', assuming rebus (as '%s')" % (filename, ch, cellch))